version: '3'

services:
  #PHP Service
  php:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    volumes:
      - ./src/frontend:/var/www
    networks:
      - backend

  # Nginx Service
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:      
      - ./src/frontend:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - 8000:80
      - 443:443
    networks:
      - backend
      - frontend
    depends_on:
      - php
      - db

  # Postgres Service
  db:
    container_name: postgres
    build:
      context: ./docker/db
    ports:
      - 5432:5432
    networks:
      - backend
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

networks: 
  backend:
  frontend: